manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: blank-slate-zmk-module
      url: https://github.com/petejohanson/blank-slate-zmk-module
      revision: core-zephyr-hwmv2-update
      path: modules/blank-slate-zmk-module
  self:
    path: config
